### ISSUE TITLE
Pre-commit hadolint-docker requires docker group added to sudo?

### ISSUE THREAD

**Issue by ddxv** [hadolint/hadolint#1052]
- [x] This is a bug report
- [ ] This is a feature request
- [x ] I searched existing issues before opening this one

### Expected behavior

run `pre-commit run --all-files` and hadolint-docker runs.

### Actual behavior
```
docker: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Head "http://%2Fvar%2Frun%2Fdocker.sock/_ping": dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
```

### Pre-commit.yaml

```
### DOCKER
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint-docker
```

### Question

I believe my issue is that I run docker as `sudo docker...` and have not added my user to a docker group ie:

```
$ sudo groupadd docker
$ sudo usermod -aG docker $USER
```

Is the above an expected step before adding `hadolint-docker` to pre-commit? If so should I add that, or something similar, to the integration doc?

**Additional environment details (OS, stack version, etc.)**
Fresh install of Fedora release 41 (Forty One)
