### ISSUE TITLE
Please readd /bin/sh to hadolint docker image

### ISSUE THREAD

**Issue by mrueg** [hadolint/hadolint#218]
- [x] This is a bug report
- [ ] This is a feature request
- [x] I searched existing issues before opening this one

### Expected behavior
/bin/sh available on hadolint docker image
### Actual behavior
None found
### Steps to reproduce the behavior
Since this change, there's no /bin/sh in the hadolint docker image:
https://github.com/hadolint/hadolint/commit/8c2642232cbc4daa27f553bc3b4f1ddb63ba4b70

I added hadolint to my CI system and which executes steps within a shell, that make /bin/sh necessary. Before building my own images, I'd like to ask if you could you consider readding /bin/sh and maybe publish the other one as hadolint-minimal?

**Comment by lorenzo** [comment]
what ci system do you use?

**Comment by mrueg** [comment]
I used drone CI (https://github.com/drone/drone). My CI config looks similar to this:
```
lint:
    image: hadolint/hadolint
    group: lint
    pull: true
    commands:
      - hadolint --version
      - hadolint Dockerfile
```
