### ISSUE TITLE
Alpine image doesn't come with sh

### ISSUE THREAD

**Issue by jpds** [hadolint/hadolint#269]
- [x] This is a bug report

### Expected behavior

I'm configuring Drone CI (https://drone.io/) to have Hadolint as a validation stage with:

```
pipeline:
  hadolint:
    group: validate
    image: hadolint/hadolint:latest
    commands:
      - hadolint --version
      - hadolint Dockerfile
```

However, this fails with:

```
Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": unknown
```

`hadolint/hadolint:latest-debian` works fine. 

### Steps to reproduce the behavior

1. Copy and paste the above into a `.drone.yml` file
2. Download the drone go binary
3. Run `drone exec`
