### ISSUE TITLE
build and release an arm64 version of hadolint

### ISSUE THREAD

**Issue by vielmetti** [hadolint/hadolint#411]
- [ ] This is a bug report
- [x] This is a feature request
- [x] I searched existing issues before opening this one

Previously #314 noting failures.

### Expected behavior

Releases directory and docker image published to include a linux/arm64 version of `hadolint`.

### Actual behavior

Only linux/amd64 versions are available.

### Steps to reproduce the behavior

See https://hub.docker.com/r/hadolint/hadolint/tags

**Additional environment details (OS, stack version, etc.)**

Please note that substantial progress has been made on Haskell for aarch64 (arm64), and the report I have from my colleague who has gone through this motivates this work by noting that `hadolint` is part of the build process for several Kubernetes components, and that it can be built by using Haskell's published `stack` binaries.

**Comment by lorenzo** [comment]
Is there any free CI service supporting arm64?

**Comment by vielmetti** [comment]
Yes @lorenzo there is Travis CI - details about their progress here https://blog.travis-ci.com/arm-architecture-adoption-grows-on-travis-ci - as well as Drone Cloud https://blog.drone.io/continuous-integration-workloads-for-arm-grow-10x/

**Comment by vielmetti** [comment]
some progress, after installing `stack` on arm64:

```
emv@01:~$ stack --version
Version 1.5.1 aarch64
```

```
emv@01:~/src/github.com/hadolint/hadolint$ stack install
Could not parse '/home/emv/src/github.com/hadolint/hadolint/stack.yaml':
Aeson exception:
Error in $['extra-deps'][0]: failed to parse field 'extra-deps': (Invalid package identifier: "ShellCheck-0.7.1@sha256:94a6ee5a38e2668204bc95fdc7539a9a4ca7230984157694409444530c23b5a4,3170","ShellCheck-0.7.1@sha256:94a6ee5a38e2668204bc95fdc7539a9a4ca7230984157694409444530c23b5a4,3170")
See http://docs.haskellstack.org/en/stable/yaml_configuration/
```

**Comment by vielmetti** [comment]
I'll note that's a pretty old version of `stack`, but trying to upgrade it fails as follows:

```
emv@01:~/src/github.com/hadolint/hadolint$ stack upgrade --binary-only
Warning: Unknown value for architecture setting: "aarch64"
Binary upgrade not yet supported on arch: OtherArch "aarch64"
```

**Comment by vielmetti** [comment]
and... `stack` has dropped arm64 binary support for now due to limits in their CI system.  https://github.com/commercialhaskell/stack/issues/2103

**Comment by tolysz** [comment]
worked! with [`stack-2.5.0.1`](http://ghcjs.tolysz.org/stack-2.5.0.1-3cbd37ab548a34cf3fc0a8277079c4cef27c1118-linux-aarch64.gz)
`$HOME/.stack/global-project/stack.yaml`
```
packages: []
resolver: lts-14.27
setup-info:
   ghc:
      linux-aarch64-nopie:
            8.2.2:
              url: "http://ghcjs.tolysz.org/ghc-8.2.2-aarch64-unknown-linux.tar.xz"
              content-length: 152979556
              sha1: 93320f0e2987c03e395369f2d6f54276c08e8e86
            8.6.3:
              url: "http://ghcjs.tolysz.org/ghc-8.6.3-aarch64-unknown-linux.tar.xz"
              content-length: 191169108
              sha1: aca53485908607126a35fdf9a513fe2f5554b6cd
            8.6.5:
              url: "http://ghcjs.tolysz.org/ghc-8.6.5-aarch64-unknown-linux.tar.xz"
              content-length: 190345900
              sha1: 5a4473e11b4ebc15f9c2a5d0b131d04b8301a5ab
```
`install llvm-6.0 libgmp-dev`
`stack setup`

`PATH=/usr/lib/llvm-6.0/bin/:$PATH stack install hadolint`
