### ISSUE TITLE
CircleCI fails after 2.0 release

### ISSUE THREAD

**Issue by jandudulski** [hadolint/hadolint#577]
- [x] This is a bug report
- [ ] This is a feature request
- [ ] I searched existing issues before opening this one

### Expected behavior

Works as with 1.x version.

### Actual behavior

Error message:

```
CircleCI was unable to run the job runner because we were unable to execute commands in build container.

This typically means that the build container entrypoint or command is terminating the container prematurely, or interfering with executed commands.  Consider clearing entrypoint/command values and try again.
```

### Steps to reproduce the behavior

Below part of my circleci config

```
jobs:
  hadolint:
    docker:
      - image: hadolint/hadolint

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Lint Dockerfile
          command:
            hadolint Dockerfile
```
